# Generated by Django 6.1 on 2026-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_reference', models.CharField(blank=True, default='', max_length=256)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('invalid', 'Invalid'), ('not_eligible', 'Not Eligible')], default='pending', max_length=32)),
                ('eligible', models.BooleanField(default=False)),
                ('requirement_results', models.JSONField(blank=True, default=list)),
                ('policy_id', models.CharField(blank=True, default='', max_length=64)),
                ('policy_version', models.CharField(blank=True, default='', max_length=32)),
                ('midnight_proof_valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
