# Generated by Django 6.1 on 2026-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('academic', 'Academic Credential'), ('enrollment', 'Enrollment Credential'), ('financial', 'Financial Eligibility Credential'), ('identity', 'Identity/Age Credential')], max_length=32)),
                ('issuer', models.CharField(max_length=255)),
                ('commitment', models.CharField(blank=True, default='', max_length=128)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('household_income', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('years_completed', models.IntegerField(blank=True, null=True)),
                ('enrollment_status', models.CharField(blank=True, default='', max_length=32)),
                ('university', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['credential_type'],
            },
        ),
    ]
